// <auto-generated />
using System;
using EmployeeApp.API.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeApp.API.Migrations
{
    [DbContext(typeof(EmployeeApiDbContext))]
    partial class EmployeeApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeApp.API.Domain.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HireDate = new DateTime(2023, 3, 8, 16, 23, 53, 657, DateTimeKind.Local).AddTicks(4312),
                            Name = "CEO"
                        },
                        new
                        {
                            Id = 2,
                            HireDate = new DateTime(2023, 3, 10, 16, 23, 53, 657, DateTimeKind.Local).AddTicks(4369),
                            ManagerId = 1,
                            Name = "Director One"
                        },
                        new
                        {
                            Id = 3,
                            HireDate = new DateTime(2023, 3, 12, 16, 23, 53, 657, DateTimeKind.Local).AddTicks(4371),
                            ManagerId = 1,
                            Name = "Director Two"
                        },
                        new
                        {
                            Id = 4,
                            HireDate = new DateTime(2023, 3, 14, 16, 23, 53, 657, DateTimeKind.Local).AddTicks(4374),
                            ManagerId = 2,
                            Name = "Manager One"
                        },
                        new
                        {
                            Id = 5,
                            HireDate = new DateTime(2023, 3, 16, 16, 23, 53, 657, DateTimeKind.Local).AddTicks(4376),
                            ManagerId = 2,
                            Name = "Manager Two"
                        },
                        new
                        {
                            Id = 6,
                            HireDate = new DateTime(2023, 3, 18, 16, 23, 53, 657, DateTimeKind.Local).AddTicks(4379),
                            ManagerId = 3,
                            Name = "Manager Three"
                        },
                        new
                        {
                            Id = 7,
                            HireDate = new DateTime(2023, 3, 20, 16, 23, 53, 657, DateTimeKind.Local).AddTicks(4381),
                            ManagerId = 4,
                            Name = "Regular Employee One"
                        },
                        new
                        {
                            Id = 8,
                            HireDate = new DateTime(2023, 3, 23, 16, 23, 53, 657, DateTimeKind.Local).AddTicks(4383),
                            ManagerId = 4,
                            Name = "Regular Employee Two"
                        },
                        new
                        {
                            Id = 9,
                            HireDate = new DateTime(2023, 3, 26, 16, 23, 53, 657, DateTimeKind.Local).AddTicks(4386),
                            ManagerId = 4,
                            Name = "Regular Employee Three"
                        },
                        new
                        {
                            Id = 10,
                            HireDate = new DateTime(2023, 3, 29, 16, 23, 53, 657, DateTimeKind.Local).AddTicks(4388),
                            ManagerId = 5,
                            Name = "Regular Employee Four"
                        },
                        new
                        {
                            Id = 11,
                            HireDate = new DateTime(2023, 4, 1, 16, 23, 53, 657, DateTimeKind.Local).AddTicks(4390),
                            ManagerId = 5,
                            Name = "Regular Employee Five"
                        },
                        new
                        {
                            Id = 12,
                            HireDate = new DateTime(2023, 4, 4, 16, 23, 53, 657, DateTimeKind.Local).AddTicks(4393),
                            ManagerId = 6,
                            Name = "Regular Employee Six"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
